name: Build and Publish Add-on

on:
  push:
    branches: [ main, master ]
    paths: [ "ha_to_163/**" ]
  pull_request:
    branches: [ main, master ]
    paths: [ "ha_to_163/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/dmxmj/ha-addon-163-gateway
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ github.event.repository.default_branch }}
            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.repository.default_branch }}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ha_to_163
          file: ha_to_163/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
