name: Build Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👇 调试用：确认目录结构
      - name: Debug: List directories
        run: |
          echo "Root directory:"
          ls -la
          echo "ha-addon-163-gateway/:"
          ls -la ha-addon-163-gateway/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ha-addon-163-gateway/ha_to_163
          file: ha-addon-163-gateway/ha_to_163/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/dmxmj/ha-to-163-gateway:latest
          provenance: mode=max
