name: 构建多架构镜像

on:
  push:
    branches: [ main ]
    paths:
      - 'ha-addon-163-gateway/**'  # 修正目录名拼写
      - '.github/workflows/main.yml'  # 修正工作流文件名

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取插件版本（从config.json）
        id: version
        run: |
          # 修正config.json的实际路径（位于ha_to_163子目录下）
          echo "VERSION=$(jq -r '.version' ha-addon-163-gateway/ha_to_163/config.json)" >> $GITHUB_OUTPUT

      - name: 构建并推送多架构镜像
        uses: docker/build-push-action@v5
        with:
          context: ./ha-addon-163-gateway/ha_to_163  # 修正Dockerfile所在目录
          file: ./ha-addon-163-gateway/ha_to_163/Dockerfile  # 修正Dockerfile路径
          platforms: linux/amd64,linux/arm64,linux/armv7,linux/i386  # 匹配config.json中的arch
          push: true
          tags: |
            ghcr.io/dmxmj/ha-to-163-gateway/amd64:${{ steps.version.outputs.VERSION }}
            ghcr.io/dmxmj/ha-to-163-gateway/arm64:${{ steps.version.outputs.VERSION }}
            ghcr.io/dmxmj/ha-to-163-gateway/armv7:${{ steps.version.outputs.VERSION }}
            ghcr.io/dmxmj/ha-to-163-gateway/i386:${{ steps.version.outputs.VERSION }}
          build-args: |
            BUILD_FROM=homeassistant/{arch}-base:latest
            BUILD_VERSION=${{ steps.version.outputs.VERSION }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
