name: 构建多架构镜像

on:
  push:
    branches: [ main ]
    paths:
      - 'ha-addon-163-gateway/**'  # 修正目录名拼写（gatewa → gateway）
      - '.github/workflows/main.yml'  # 确保工作流文件名正确

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 调试路径和文件
        run: |
          echo "当前目录结构："
          ls -R ha-addon-163-gateway
          echo "检查 config.json 是否存在："
          if [ -f "ha-addon-163-gateway/ha_to_163/config.json" ]; then
            echo "存在，版本号：$(jq -r '.version' ha-addon-163-gateway/ha_to_163/config.json)"
          else
            echo "不存在！" && exit 1
          fi

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取插件版本（从config.json）
        id: version
        run: |
          echo "VERSION=$(jq -r '.version' ha-addon-163-gateway/ha_to_163/config.json)" >> $GITHUB_OUTPUT

      - name: 构建并推送多架构镜像
        uses: docker/build-push-action@v5
        with:
          context: ./ha-addon-163-gateway/ha_to_163
          file: ./ha-addon-163-gateway/ha_to_163/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/dmxmj/ha-to-163-gateway/amd64:${{ steps.version.outputs.VERSION }}
            ghcr.io/dmxmj/ha-to-163-gateway/aarch64:${{ steps.version.outputs.VERSION }}
          build-args: |
            BUILD_FROM=homeassistant/{arch}-base:latest
            BUILD_VERSION=${{ steps.version.outputs.VERSION }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
